# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Challenge.create(name: "Beginning HTML", time_length: "2.75")
Challenge.create(name: "Beginning CSS", time_length: "4")
Challenge.create(name: "Flow Control", time_length: "2.25")
Challenge.create(name: "Calculate the Mode", time_length: "2")
Challenge.create(name: "Calculate the Median", time_length: "2.75")
Challenge.create(name: "Nested Data Structures", time_length: "2")
Challenge.create(name: "Validate Credit Card", time_length: "2.5")

Day.create(name: "Sunday")
Day.create(name: "Monday")
Day.create(name: "Tuesday")
Day.create(name: "Wednesday")
Day.create(name: "Thursday")
Day.create(name: "Friday")
Day.create(name: "Saturday")

Hour.create(hrf: "1", suffix: "am")
Hour.create(hrf: "2", suffix: "am")
Hour.create(hrf: "3", suffix: "am")
Hour.create(hrf: "4", suffix: "am")
Hour.create(hrf: "5", suffix: "am")
Hour.create(hrf: "6", suffix: "am")
Hour.create(hrf: "7", suffix: "am")
Hour.create(hrf: "8", suffix: "am")
Hour.create(hrf: "9", suffix: "am")
Hour.create(hrf: "10", suffix: "am")
Hour.create(hrf: "11", suffix: "am")
Hour.create(hrf: "12", suffix: "am")
Hour.create(hrf: "1", suffix: "pm")
Hour.create(hrf: "2", suffix: "pm")
Hour.create(hrf: "3", suffix: "pm")
Hour.create(hrf: "4", suffix: "pm")
Hour.create(hrf: "5", suffix: "pm")
Hour.create(hrf: "6", suffix: "pm")
Hour.create(hrf: "7", suffix: "pm")
Hour.create(hrf: "8", suffix: "pm")
Hour.create(hrf: "9", suffix: "pm")
Hour.create(hrf: "10", suffix: "pm")
Hour.create(hrf: "11", suffix: "pm")
Hour.create(hrf: "12", suffix: "pm")
